---
title: "practice with rmarkdown"
author: "jasmin"
date: "3/3/2021"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path="../Output/")
```

# Introduction
Today, we will use **Palmer penguins** to manipulate figures in RMarkdown.

# Load Libraries


```{r}
library(palmerpenguins)
library(tidyverse)
library(here)
library(kableExtra)
```

# Make a plot
```{r PengFig, fig.align="center", fig.cap="This is a figure of penguin flipper.", echo=FALSE}
PenguinFigure<- penguins %>%
  ggplot(aes(x = species, y = flipper_length_mm, color = island)) +
  geom_boxplot()

PenguinFigure
```

# Make a table

| table 1 | col 2 |
|:--------|:-----:|
|1        |2      |

I use a col to decide alignment.

| Time  | Session  | Topic      |
|:------|:--------:|-----------:|
| _left_| _center_ | _right_    |


```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm=TRUE)) %>%
  kbl() %>%
  kable_classic() %>%
  row_spec(2, bold = TRUE, color = "white", background = "red")
```

